import {auth,db} from './firebase-init.js';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {doc,getDoc,collection,addDoc,getDocs,query,orderBy,serverTimestamp,deleteDoc} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const login=document.querySelector('#loginForm'), gate=document.querySelector('#loginGate'), app=document.querySelector('#adminApp'), error=document.querySelector('#loginError');
async function isAdmin(user){const snap=await getDoc(doc(db,'users',user.uid));return snap.exists()&&snap.data().role==='admin'}
login?.addEventListener('submit',async e=>{e.preventDefault();error.textContent='Signing in…';error.classList.remove('hidden');try{await signInWithEmailAndPassword(auth,login.email.value,login.password.value)}catch(err){error.textContent='Invalid account or password.'}});
$('#logout')?.addEventListener('click',()=>signOut(auth));
onAuthStateChanged(auth,async user=>{if(!user){gate.classList.remove('hidden');app.classList.add('hidden');return}if(await isAdmin(user)){gate.classList.add('hidden');app.classList.remove('hidden');document.querySelector('#adminEmailLabel').textContent=user.email||'';loadAll()}else{await signOut(auth);error.textContent='This account does not have administrator access.';error.classList.remove('hidden')}});
async function loadAll(){await Promise.all([loadEmployees(),loadApplications(),loadInquiries()])}
async function loadEmployees(){const tb=$('#employeeRows');tb.innerHTML='<tr><td colspan="5">Loading…</td></tr>';const snap=await getDocs(collection(db,'employees'));tb.innerHTML='';snap.forEach(x=>{const d=x.data();const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(d.employeeId)}</td><td>${esc(d.name)}</td><td>${esc(d.role)}</td><td>${esc(d.unit)}</td><td><button class="btn btn-outline" data-delete="${x.id}">Delete</button></td>`;tb.appendChild(tr)});$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this employee record?')){await deleteDoc(doc(db,'employees',b.dataset.delete));loadEmployees()}})}
async function loadApplications(){const tb=$('#applicationRows');tb.innerHTML='';const snap=await getDocs(query(collection(db,'applications'),orderBy('createdAt','desc')));snap.forEach(x=>{const d=x.data();const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(d.name)}</td><td>${esc(d.email)}</td><td>${esc(d.role)}</td><td><span class="pill">${esc(d.status||'new')}</span></td>`;tb.appendChild(tr)})}
async function loadInquiries(){const tb=$('#inquiryRows');tb.innerHTML='';const snap=await getDocs(query(collection(db,'inquiries'),orderBy('createdAt','desc')));snap.forEach(x=>{const d=x.data();const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(d.name)}</td><td>${esc(d.email)}</td><td>${esc(d.department)}</td><td>${esc(d.message).slice(0,100)}</td>`;tb.appendChild(tr)})}
$('#employeeForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);await addDoc(collection(db,'employees'),{employeeId:fd.get('employeeId'),name:fd.get('name'),role:fd.get('role'),unit:fd.get('unit'),email:fd.get('email'),phone:fd.get('phone'),createdAt:serverTimestamp()});e.target.reset();loadEmployees()});
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('[data-view]').forEach(x=>x.classList.add('hidden'));$(`[data-view="${b.dataset.tab}"]`).classList.remove('hidden')});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
